# Generated by Django 5.2.6 on 2025-10-10 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("small", "Small (1–4)"),
                            ("medium", "Medium (4–8)"),
                            ("large", "Large (8+)"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("meeting", "Meeting room"),
                            ("conference", "Conference room"),
                            ("huddle", "Huddle room"),
                            ("training", "Training room"),
                            ("board", "Board room"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("capacity", models.PositiveIntegerField(default=1)),
                ("location", models.CharField(blank=True, max_length=120)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["size"], name="booking_roo_size_ee76c3_idx"),
                    models.Index(
                        fields=["category"], name="booking_roo_categor_d23463_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=140)),
                ("start_at", models.DateTimeField()),
                ("end_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="booking.room",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_at"],
                "indexes": [
                    models.Index(
                        fields=["room", "start_at"],
                        name="booking_boo_room_id_b7e03a_idx",
                    ),
                    models.Index(
                        fields=["room", "end_at"], name="booking_boo_room_id_37a2b5_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("end_at__gt", models.F("start_at"))),
                        name="booking_end_after_start",
                    )
                ],
            },
        ),
    ]
