# Generated by Django 5.2.6 on 2025-10-31 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=12)),
                ('pinned', models.BooleanField(default=False, help_text='Pin to top in lists')),
                ('publish_at', models.DateTimeField(blank=True, help_text='Start showing at this time (optional)', null=True)),
                ('expire_at', models.DateTimeField(blank=True, help_text='Stop showing after this time (optional)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to=settings.AUTH_USER_MODEL)),
                ('departments', models.ManyToManyField(blank=True, related_name='announcements', to='departments.department')),
            ],
            options={
                'ordering': ['-pinned', '-publish_at', '-created_at'],
                'indexes': [models.Index(fields=['status', 'publish_at'], name='comms_annou_status_b0a498_idx'), models.Index(fields=['pinned'], name='comms_annou_pinned_43037d_idx'), models.Index(fields=['slug'], name='announcement_slug_idx')],
            },
        ),
    ]
